modifies test cases and removed redundant tests Modified 'validate' scipt

diff --git a/validation/validate b/validation/validate
--- a/validation/validate
+++ b/validation/validate
@@ -34,6 +34,9 @@ for iter in 1 2 ; do
      EXEC_PASS_LOG="$RESULTS_DIR/exec_pass_$DATE.log"
      COMPILE_FAIL_LOG="$RESULTS_DIR/compile_fail_$DATE.log"
      EXEC_FAIL_LOG="$RESULTS_DIR/exec_fail_$DATE.log"
+     for temp in $COMPILE_PASS_LOG $EXEC_PASS_LOG $COMPILE_FAIL_LOG $EXEC_FAIL_LOG; do
+        echo "*******CONFORMANCE TESTS*******" >> $temp
+     done
   else
      echo "*******NON-CONFORMANCE TESTS*******"
      echo "SPEC_IDX COMPILE_OP EXECUTE_OP DESCRIPTION"
@@ -45,12 +48,17 @@ for iter in 1 2 ; do
      EXEC_PASS_LOG="$RESULTS_DIR/exec_fail_$DATE.log"
      COMPILE_FAIL_LOG="$RESULTS_DIR/compile_pass_$DATE.log"
      EXEC_FAIL_LOG="$RESULTS_DIR/exec_pass_$DATE.log"
+     for temp in $COMPILE_PASS_LOG $EXEC_PASS_LOG $COMPILE_FAIL_LOG $EXEC_FAIL_LOG; do
+        echo "*******NON-CONFORMANCE TESTS*******" >> $temp
+     done
   fi
-# for file in `ls *.f90`; do
- for file in "item_008.005.004.f90"; do
+ for file in `ls *.f90`; do
+ #for file in "item_008.005.004.f90"; do
    COMPILE_STATUS="UNKNOWN"
    EXEC_STATUS="N/A"
    SPEC_IDX="`echo "$file" |sed 's/.f90//'| sed 's/item_//'`"
+   DESCRIPTION="`cat description | grep "$file" | sed s/"$file"//`"
+
    if [ "$V" == "1" ]; then
       echo "$FC $FFLAGS $CURRENT_PATH/$file -o $ROOT/executables/$file.x 2>$CURRENT_PATH/compile_output/$file.compile.out && echo 2 || echo 3"
       echo "perl $ROOT/timedexec.pl $TIMEOUT \"cafrun -n 4 $ROOT/executables/$file.x\"  2>&1 && echo 1 || echo -1"
@@ -61,10 +69,8 @@ for iter in 1 2 ; do
    if [ $COMPILE_OUT -eq 2 ]; then
      COMPILE_STATUS="$PASS_OUT"
      echo -n -e "\t\t$COMPILE_STATUS"
-     echo "$SPEC_IDX"  >> $COMPILE_PASS_LOG
-     # EXEC_OUT=`perl $ROOT/timedexec.pl $TIMEOUT "cafrun -n 4 $ROOT/executables/$file.x"  2>&1 && echo 1 || echo -1`
-     echo "perl $ROOT/timedexec.pl $TIMEOUT \"cafrun -n 4 $ROOT/executables/$file.x\"  2>&1 && echo 1 || echo -1"
-     EXEC_OUT=`perl $ROOT/timedexec.pl $TIMEOUT "cafrun -n 4 $ROOT/executables/$file.x"  2>&1 && echo 1 || echo -1`
+     echo -e "$file \t $DESCRIPTION">> $COMPILE_PASS_LOG
+     EXEC_OUT=`perl $ROOT/timedexec.pl $TIMEOUT " $ROOT/executables/$file.x"  2>&1 && echo 1 || echo -1`
      if [ "$EXEC_OUT" == "-1" ]; then
          EXEC_STATUS="RUNTIME ERROR"
          echo "$file" >> $EXEC_FAIL_LOG
@@ -73,30 +79,26 @@ for iter in 1 2 ; do
           VERIFICATION=`echo "$EXEC_OUT" | grep ERROR | awk '{print $5}'`
           if [ "$VERIFICATION" == "" ]; then
              EXEC_STATUS="$PASS_OUT"
-             echo "$file" >> $EXEC_PASS_LOG
+             echo -e "$file \t $DESCRIPTION" >> $EXEC_PASS_LOG
           else
              EXEC_STATUS="$FAIL_OUT"
-             echo "$file" >> $EXEC_FAIL_LOG
+             echo -e "$file \t $DESCRIPTION" >> $EXEC_FAIL_LOG
           fi
      fi
    else
      COMPILE_STATUS="$FAIL_OUT"
-     echo "$file" >>$COMPILE_FAIL_LOG
+     echo -e "$file \t $DESCRIPTION" >>$COMPILE_FAIL_LOG
      echo -n -e "\t\t$COMPILE_STATUS"
    fi
-   echo -e "\t $EXEC_STATUS ` cat description | grep "$file" | sed s/"$file"//`"
+   echo -e "\t\t$EXEC_STATUS \t$DESCRIPTION"
   done
   cd $ROOT
 done
 
 
 # Sending an email notification
-if [ (-f $COMPILE_FAIL_LOG) && (-f $EXEC_FAIL_LOG) ]; then
 tar -rf $ATTACH  $COMPILE_FAIL_LOG $EXEC_FAIL_LOG
 mutt -s "$SUBJ" -a $ATTACH $EMAIL < "Failed logs attached"
-fi
 
-echo "Test completed"
-
-
+echo "Test completed !!!"
 
