improving tests... adding makefiles
contributor: Siddhartha

diff --git a/validation/validate b/validation/validate
--- a/validation/validate
+++ b/validation/validate
@@ -7,12 +7,14 @@ PASS_OUT=PASS
 FAIL_OUT=FAIL
 RESULTS_DIR="$ROOT/results"
 
-SUBJ="UHCAF-Testsuite validation results"
-EMAIL="siddharthajana24@gmail.com,dreachem@gmail.com"
-ATTACH="$ROOT/uhcaf_results_$DATE.tar"
+SUBJ="$COMPILER-Testsuite validation results"
+EMAIL="siddharthajana24@gmail.com"
+ATTACH="$ROOT/results/uhcaf_results_$DATE.tar"
+echo "Failed Logs Attached" > $ROOT/email_body.tmp
 
 cd $RESULTS_DIR
-rm -rf compile_failed.log  compile_passed.log  exec_failed.log exec_passed.log
+mv *.log ./HISTORY
+mv *.tar ./HISTORY
 cd $ROOT
 
 if [ ! -f $ROOT/../config/CONFIG ]; then
@@ -22,7 +24,7 @@ fi
 
 source $ROOT/../config/CONFIG
 
-for iter in 1 2 ; do
+for iter in 1 ; do
   if [ "$iter" == "1" ]; then
      echo "*******CONFORMANCE TESTS*******"
      echo "SPEC_IDX COMPILE_OP EXECUTE_OP DESCRIPTION"
@@ -30,10 +32,10 @@ for iter in 1 2 ; do
      PASS_OUT="PASS"
      FAIL_OUT="FAIL"
      cd $CURRENT_PATH
-     COMPILE_PASS_LOG="$RESULTS_DIR/compile_pass_$DATE.log"
-     EXEC_PASS_LOG="$RESULTS_DIR/exec_pass_$DATE.log"
-     COMPILE_FAIL_LOG="$RESULTS_DIR/compile_fail_$DATE.log"
-     EXEC_FAIL_LOG="$RESULTS_DIR/exec_fail_$DATE.log"
+     COMPILE_PASS_LOG="$RESULTS_DIR/$FC\_compile_pass_$DATE.log"
+     EXEC_PASS_LOG="$RESULTS_DIR/$FC\_exec_pass_$DATE.log"
+     COMPILE_FAIL_LOG="$RESULTS_DIR/$FC\_compile_fail_$DATE.log"
+     EXEC_FAIL_LOG="$RESULTS_DIR/$FC\_exec_fail_$DATE.log"
      for temp in $COMPILE_PASS_LOG $EXEC_PASS_LOG $COMPILE_FAIL_LOG $EXEC_FAIL_LOG; do
         echo "*******CONFORMANCE TESTS*******" >> $temp
      done
@@ -44,10 +46,10 @@ for iter in 1 2 ; do
      PASS_OUT="FAIL"
      FAIL_OUT="PASS"
      cd $CURRENT_PATH
-     COMPILE_PASS_LOG="$RESULTS_DIR/compile_fail_$DATE.log"
-     EXEC_PASS_LOG="$RESULTS_DIR/exec_fail_$DATE.log"
-     COMPILE_FAIL_LOG="$RESULTS_DIR/compile_pass_$DATE.log"
-     EXEC_FAIL_LOG="$RESULTS_DIR/exec_pass_$DATE.log"
+     COMPILE_PASS_LOG="$RESULTS_DIR/$FC\_compile_fail_$DATE.log"
+     EXEC_PASS_LOG="$RESULTS_DIR/$FC\_exec_fail_$DATE.log"
+     COMPILE_FAIL_LOG="$RESULTS_DIR/$FC\_compile_pass_$DATE.log"
+     EXEC_FAIL_LOG="$RESULTS_DIR/${FC}_exec_pass_$DATE.log"
      for temp in $COMPILE_PASS_LOG $EXEC_PASS_LOG $COMPILE_FAIL_LOG $EXEC_FAIL_LOG; do
         echo "*******NON-CONFORMANCE TESTS*******" >> $temp
      done
@@ -61,7 +63,7 @@ for iter in 1 2 ; do
 
    if [ "$V" == "1" ]; then
       echo "$FC $FFLAGS $CURRENT_PATH/$file -o $ROOT/executables/$file.x 2>$CURRENT_PATH/compile_output/$file.compile.out && echo 2 || echo 3"
-      echo "perl $ROOT/timedexec.pl $TIMEOUT \"cafrun -n 4 $ROOT/executables/$file.x\"  2>&1 && echo 1 || echo -1"
+      echo "perl $ROOT/timedexec.pl $TIMEOUT \"$LAUNCHER $ROOT/executables/$file.x\"  2>&1 && echo 1 || echo -1"
    fi
    echo -n $SPEC_IDX
    COMPILE_OUT=`$FC $FFLAGS $CURRENT_PATH/$file -o $ROOT/executables/$file.x 2>$CURRENT_PATH/compile_output/$file.compile.out && echo 2 || echo 3`
@@ -70,7 +72,7 @@ for iter in 1 2 ; do
      COMPILE_STATUS="$PASS_OUT"
      echo -n -e "\t\t$COMPILE_STATUS"
      echo -e "$file \t $DESCRIPTION">> $COMPILE_PASS_LOG
-     EXEC_OUT=`perl $ROOT/timedexec.pl $TIMEOUT " $ROOT/executables/$file.x"  2>&1 && echo 1 || echo -1`
+     EXEC_OUT=`perl $ROOT/timedexec.pl $TIMEOUT "$LAUNCHER  $ROOT/executables/$file.x"  2>&1 && echo 1 || echo -1`
      if [ "$EXEC_OUT" == "-1" ]; then
          EXEC_STATUS="RUNTIME ERROR"
          echo "$file" >> $EXEC_FAIL_LOG
@@ -98,7 +100,8 @@ done
 
 # Sending an email notification
 tar -rf $ATTACH  $COMPILE_FAIL_LOG $EXEC_FAIL_LOG
-mutt -s "$SUBJ" -a $ATTACH $EMAIL < "Failed logs attached"
+mutt -s "$SUBJ" -a $ATTACH $EMAIL < $ROOT/email_body.tmp
+rm -rf $ROOT/email_body.tmp
 
 echo "Test completed !!!"
 
